// Central constants + mock data extracted from the original YourAllyApp.jsx

export const C = {
  brand: "#E8871A",
  brandDark: "#B8650E",
  brandLight: "#FDF3E7",
  brandPale: "#FEF9F2",
  funeralBg: "#F7F6F4",
  funeralText: "#4A4845",
  funeralMuted: "#8A8784",
  funeralAccent: "#6B6A68",
  success: "#2D8A5B",
  successBg: "#EAF5EF",
  info: "#2563EB",
  infoBg: "#EFF6FF",
  bg: "#FAFAF8",
  surface: "#FFFFFF",
  border: "rgba(0,0,0,0.08)",
  borderMed: "rgba(0,0,0,0.14)",
  text: "#1A1917",
  textMuted: "#6B6968",
  textFaint: "#A09E9C",
};

// Funeral-only palette — NO brand orange anywhere in this palette
export const FC = {
  bg: "#F7F6F4",
  text: "#4A4845",
  muted: "#8A8784",
  accent: "#6B6A68",
  border: "rgba(0,0,0,0.10)",
  surface: "#FFFFFF",
  step: "#D1D0CE",
};

export const CHEFS = [
  {
    id: 1,
    name: "Priya Sharma",
    initials: "PS",
    experience: "8 years",
    cuisines: ["Bengali", "North Indian"],
    rating: 4.8,
    price: 350,
    mode: "both",
    verified: true,
    avatarBg: "#FDF3E7",
    avatarColor: "#B8650E",
  },
  {
    id: 2,
    name: "Arjun Mehta",
    initials: "AM",
    experience: "12 years",
    cuisines: ["South Indian", "Continental"],
    rating: 4.9,
    price: 420,
    mode: "physical",
    verified: true,
    avatarBg: "#EFF6FF",
    avatarColor: "#2563EB",
  },
  {
    id: 3,
    name: "Sunita Devi",
    initials: "SD",
    experience: "5 years",
    cuisines: ["Bengali", "Chinese"],
    rating: 4.7,
    price: 200,
    mode: "virtual",
    verified: true,
    empowered: true,
    avatarBg: "#EAF5EF",
    avatarColor: "#2D8A5B",
  },
  {
    id: 4,
    name: "Rahul Das",
    initials: "RD",
    experience: "10 years",
    cuisines: ["North Indian", "Mughlai"],
    rating: 4.6,
    price: 380,
    mode: "both",
    verified: true,
    avatarBg: "#F5F0FF",
    avatarColor: "#7C3AED",
  },
];

export const RECIPES = [
  {
    id: 1,
    name: "Bengali Fish Curry",
    category: "Lunch",
    cuisine: "Bengali",
    time: "45 min",
    difficulty: "Medium",
    servings: 4,
    ingredients: [
      { name: "Rohu fish", qty: 500, unit: "g" },
      { name: "Mustard oil", qty: 3, unit: "tbsp" },
      { name: "Onions", qty: 2, unit: "medium" },
      { name: "Tomatoes", qty: 2, unit: "medium" },
      { name: "Turmeric powder", qty: 0.5, unit: "tsp" },
      { name: "Red chilli powder", qty: 1, unit: "tsp" },
      { name: "Cumin seeds", qty: 0.5, unit: "tsp" },
      { name: "Salt", qty: 1, unit: "tsp" },
      { name: "Water", qty: 250, unit: "ml" },
    ],
    steps: [
      "Clean and marinate fish with turmeric and salt for 15 minutes.",
      "Heat mustard oil in a pan until smoking, then reduce flame.",
      "Fry fish pieces until golden brown on both sides. Set aside.",
      "In the same oil, add cumin seeds and let them splutter.",
      "Add chopped onions and sauté until golden brown.",
      "Add tomatoes and cook until soft and pulpy.",
      "Add remaining spices and cook for 2 minutes.",
      "Add fried fish and water. Simmer for 10 minutes.",
      "Serve hot with steamed rice.",
    ],
  },
  {
    id: 2,
    name: "Paneer Butter Masala",
    category: "Dinner",
    cuisine: "North Indian",
    time: "35 min",
    difficulty: "Easy",
    servings: 4,
    ingredients: [
      { name: "Paneer", qty: 250, unit: "g" },
      { name: "Butter", qty: 2, unit: "tbsp" },
      { name: "Fresh cream", qty: 60, unit: "ml" },
      { name: "Tomato purée", qty: 200, unit: "ml" },
      { name: "Cashew paste", qty: 2, unit: "tbsp" },
      { name: "Garam masala", qty: 0.5, unit: "tsp" },
      { name: "Kashmiri red chilli", qty: 1, unit: "tsp" },
      { name: "Salt", qty: 1, unit: "tsp" },
    ],
    steps: [
      "Melt butter in a pan over medium heat.",
      "Add tomato purée and cook for 5 minutes, stirring occasionally.",
      "Add cashew paste and stir to combine well.",
      "Add all spices and cook for 2 minutes.",
      "Add paneer cubes and fold gently into the gravy.",
      "Pour in fresh cream and simmer for 5 minutes.",
      "Serve hot garnished with cream and fresh coriander.",
    ],
  },
  {
    id: 3,
    name: "Classic Masala Dosa",
    category: "Breakfast",
    cuisine: "South Indian",
    time: "40 min",
    difficulty: "Easy",
    servings: 2,
    ingredients: [
      { name: "Dosa batter", qty: 500, unit: "ml" },
      { name: "Potatoes", qty: 3, unit: "medium" },
      { name: "Onions", qty: 1, unit: "large" },
      { name: "Green chillies", qty: 2, unit: "chopped" },
      { name: "Mustard seeds", qty: 0.5, unit: "tsp" },
      { name: "Curry leaves", qty: 8, unit: "pieces" },
      { name: "Turmeric powder", qty: 0.25, unit: "tsp" },
      { name: "Oil/Ghee", qty: 2, unit: "tbsp" },
      { name: "Salt", qty: 0.75, unit: "tsp" },
    ],
    steps: [
      "Boil and mash potatoes gently. Slice onions finely.",
      "Heat oil in a pan, add mustard seeds, curry leaves, and green chillies.",
      "Add onions and sauté until soft and transparent.",
      "Add turmeric powder, salt, and mashed potatoes. Mix thoroughly and cook for 3 minutes. Set aside.",
      "Heat a flat tawa on medium heat, sprinkle water, and wipe it dry.",
      "Spread a ladleful of dosa batter in a circular motion to form a thin, crisp layer.",
      "Drizzle ghee/oil around the edges and cook until golden brown and crispy.",
      "Place a scoop of potato masala in the center, fold the dosa over it, and serve immediately with coconut chutney."
    ],
  },
  {
    id: 4,
    name: "Royal Butter Chicken",
    category: "Dinner",
    cuisine: "North Indian",
    time: "50 min",
    difficulty: "Medium",
    servings: 4,
    ingredients: [
      { name: "Chicken breast", qty: 500, unit: "g" },
      { name: "Yogurt", qty: 120, unit: "g" },
      { name: "Butter", qty: 3, unit: "tbsp" },
      { name: "Tomato purée", qty: 250, unit: "ml" },
      { name: "Heavy cream", qty: 80, unit: "ml" },
      { name: "Ginger-garlic paste", qty: 1.5, unit: "tbsp" },
      { name: "Kashmiri red chilli", qty: 1.5, unit: "tsp" },
      { name: "Kasturi methi", qty: 1, unit: "tsp" },
      { name: "Salt", qty: 1, unit: "tsp" },
    ],
    steps: [
      "Marinate chicken with yogurt, ginger-garlic paste, half the spices, and salt for 30 minutes.",
      "Bake or pan-fry the marinated chicken until cooked and slightly charred. Set aside.",
      "In a deep pan, melt butter and cook the tomato purée for 5-7 minutes.",
      "Add remaining spices, then fold in the cream and kasturi methi.",
      "Simmer the sauce until rich and thick, then stir in the cooked chicken.",
      "Cook together for another 5 minutes and garnish with fresh cream."
    ],
  },
  {
    id: 5,
    name: "Gourmet Lava Cake",
    category: "Snacks",
    cuisine: "Continental",
    time: "25 min",
    difficulty: "Hard",
    servings: 2,
    ingredients: [
      { name: "Dark chocolate", qty: 100, unit: "g" },
      { name: "Butter", qty: 50, unit: "g" },
      { name: "Eggs", qty: 2, unit: "pieces" },
      { name: "Powdered sugar", qty: 50, unit: "g" },
      { name: "All-purpose flour", qty: 30, unit: "g" },
      { name: "Vanilla extract", qty: 0.5, unit: "tsp" },
    ],
    steps: [
      "Preheat your oven to 200°C (390°F) and grease two ramekins with butter.",
      "Melt the dark chocolate and butter together in a microwave or double boiler until silky smooth.",
      "Whisk eggs, sugar, and vanilla extract in a separate bowl until pale and thick.",
      "Fold the melted chocolate mixture and flour gently into the whisked eggs until combined.",
      "Divide the batter evenly between the prepared ramekins.",
      "Bake for exactly 10-12 minutes until the edges are firm but the center is still soft.",
      "Cool for 1 minute, invert onto dessert plates, and dust with powdered sugar."
    ],
  },
];

export const EVENT_MANAGERS = [
  {
    id: 1,
    name: "Celebration Weddings Co.",
    location: "Kolkata",
    occasions: ["Weddings", "Anniversaries"],
    rating: 4.9,
    eventsCompleted: 150,
    contact: "+91 98765 43210",
  },
  {
    id: 2,
    name: "Festive Moments",
    location: "Howrah",
    occasions: ["Birthdays", "Corporate Events"],
    rating: 4.7,
    eventsCompleted: 87,
    contact: "+91 87654 32109",
  },
  {
    id: 3,
    name: "Puja Samaroha Team",
    location: "Kolkata",
    occasions: ["Pujas"],
    rating: 4.8,
    eventsCompleted: 200,
    contact: "+91 76543 21098",
  },
];

export const LOYALTY_TIERS = [
  {
    name: "New",
    min: 0,
    max: 2,
    discount: 0,
    multiplier: 2,
    welcome: 50,
    icon: "medal-new",
    color: "#6B6968",
    bg: "#F5F5F4",
  },
  {
    name: "Bronze",
    min: 3,
    max: 6,
    discount: 10,
    multiplier: 1.5,
    welcome: 0,
    icon: "medal-bronze",
    color: "#92400E",
    bg: "#FEF3C7",
  },
  {
    name: "Silver",
    min: 7,
    max: 14,
    discount: 15,
    multiplier: 2,
    welcome: 0,
    icon: "medal-silver",
    color: "#374151",
    bg: "#F3F4F6",
  },
  {
    name: "Gold",
    min: 15,
    max: Infinity,
    discount: 20,
    multiplier: 2.5,
    welcome: 0,
    bonus: true,
    icon: "trophy",
    color: "#92400E",
    bg: "#FFFBEB",
  },
];

export const CUISINE_OPTIONS = [
  "All Cuisines",
  "Bengali",
  "North Indian",
  "South Indian",
  "Continental",
  "Chinese",
  "Mughlai",
  "All",
];

export const OCCASIONS = [
  "All",
  "Weddings",
  "Birthdays",
  "Corporate Events",
  "Pujas",
  "Anniversaries",
];

export const RECIPE_CATEGORIES = [
  "All",
  "Breakfast",
  "Lunch",
  "Dinner",
  "Snacks",
];

export const NAV_ITEMS = [
  { id: "home", label: "Home" },
  { id: "chef", label: "Find a Chef" },
  { id: "recipes", label: "Recipes" },
  { id: "events", label: "Events" },
  { id: "funeral", label: "Funeral Support" },
  { id: "loyalty", label: "Loyalty" },
  { id: "case-study", label: "PM Case Study" },
];

export const FEATURES = [
  {
    icon: "chef",
    title: "Personal Chef",
    desc: "Book a verified chef for your home — from daily meals to special occasions.",
    bg: "#FDF3E7",
    section: "chef",
  },
  {
    icon: "recipe",
    title: "Recipe Guide",
    desc: "Explore hundreds of authentic recipes with a smart portion scaler.",
    bg: "#EFF6FF",
    section: "recipes",
  },
  {
    icon: "event",
    title: "Event Planning",
    desc: "Find local event managers for weddings, birthdays, pujas, and more.",
    bg: "#EAF5EF",
    section: "events",
  },
  {
    icon: "funeral",
    title: "Funeral Support",
    desc: "Compassionate, respectful assistance during the most difficult times.",
    bg: "#F5F5F4",
    section: "funeral",
  },
  {
    icon: "women",
    title: "Women Instructors",
    desc: "Learn from empowered women educators for cooking, skills, and more.",
    bg: "#F5F0FF",
    section: "chef",
  },
];

export const STATS = [
  { value: "20+", label: "Verified Chefs" },
  { value: "100+", label: "Happy Users" },
  { value: "15+", label: "Event Managers" },
  { value: "500+", label: "Recipes" },
];

export const RECIPE_DUMMY = RECIPES;

export const TRANSLATIONS = {"hi":{"RecipeLabel":"मग़िीन्","ingredients":"सा़क्","method":"लिली","servings":"समवीिीनक्","cuisine":"तपकमबस्","difficulty":"कवमनसप॔","time":"सनतग़","category":"लिफफसन्","Easy":"आससल","Medium":"तलफग़न","Hard":"कवमनी","Breakfast":"नसवम़्","Lunch":"नसवम़्","Dinner":"म़़मलप","Snacks":"सॐनकऐव","All":"सদफ॔","recipeSteps":["आसवम़् तपमन् लिफऩ् सािव़नक् सनमकिताक् सनतग़ नसवम़् सननसकन् तन नसवम़्.","नवतसव़क् पकबसवीस् तपकपौ लिफनप़् मव़तसवपनी पतब्.","त़तौ सवम़क् पतबककनव़ तनीत़ ़नव़ नवमौतन मन. कनव़."]},"bn":{"RecipeLabel":"রࣇसीতখন","ingredients":"নࣆকঐজ","method":"ড়ऎऊলऊ","servings":"তলঐবऎলনত","cuisine":"মনবনলऊতॐঐব","difficulty":"কবলনীনতপত","time":"ঁনতग़","category":"মীলঐআ","Easy":"ঁকব","Medium":"তসনऊनশ","Hard":"কবলনী","Breakfast":"ঁঐতনল","Lunch":"ঁঐতনল","Dinner":"ঁঐতনল","Snacks":"ঁॐঐতঐব","All":"ঁম","recipeSteps":["নࣆকঐজ হঅজ ঺অনজ ড়ऎऊতজ ড়ऎকঐজ ঺অনজ ড়ऎऊলজ নࣆকঐজ ঺অ ড়ऎকঐজ ঁ.","নࣆকঐজ হঅজ ঺অনজ ড়ऎऊতজ ড়ऎকঐজ ঺অনজ ড়ऎऊলজ নࣆকঐজ ঺অ ড়ऎকঐজ ঁ.","নࣆকঐজ হঅজ ঺অনজ ড়ऎऊতজ ড়ऎকঐজ ঺অনজ ড়ऎऊলজ নࣆকঐজ ঺অ ড়ऎকঐজ ঁ."]},"ta":{"RecipeLabel":"ஊ౦ள","ingredients":"୚ாங஥","method":"ஆேஞ","servings":"୩ாஅ்","cuisine":"૽௪ங஥","difficulty":"ஞொஆேஞ","time":"ୢ௖ஆ","category":"ஞொள","Easy":"দஙள","Medium":"ங஥ொஆ","Hard":"஥ளங౦","Breakfast":"୲౲ள୚ஙஞ","Lunch":"୲౲ள୚ஙஞ","Dinner":"୲౲ள୚ஙஞ","Snacks":"ங஥ொஆே஥","All":"૽౦ள","recipeSteps":["आसवम़् तपमन् लिफऩ् सािव़नक् सनमकिताक् सनतग़ नसवम़् सननसकन् तन नसवम़्.","नवतसव़क् पकबसवीस् तपकपौ लिफनप़् मव़तसवपनी पतब्.","त़तौ सवम़क् पतबककनव़ तनीत़ ़नव़ नवमौतन मन. कनव़."]},"te":{"RecipeLabel":"ంఒ௷ఎ௦ఠ","ingredients":"ర౲ொ௖௷஥","method":"రொ௖దஶ","servings":"௷ఎ௦஥దஶ","cuisine":"రொ௖ఎ௦஥","difficulty":"రொ௖ఎ௦஥","time":"௷ொ௖దஶ","category":"రொ௖ఎ௦஥","Easy":"ஆொ௖ఎ௦","Medium":"ங஥ொஆே","Hard":"୆௖దஶఒ","Breakfast":"ஆ௷ஶదஶే","Lunch":"୲௷ஶదஶే","Dinner":"୲௷ஶదஶే","Snacks":"௷ொ௖ఎ௦","All":"ஆ௷ஶదஶ","recipeSteps":["आसवम़् तपमन् लिफऩ् सािव़नक् सनमकिताक् सनतग़ नसवम़् सननसकन् तन नसवम़्.","नवतसव़क् पकबसवीस् तपकपौ लिफनप़् मव़तसवपनी पतब्.","त़तौ सवम़क् पतबककनव़ तनीत़ ़नव़ नवमौतन मन. कनव़."]},"mr":{"RecipeLabel":"ठासन्","ingredients":"सऔसन् ूऄ","method":"तऩ्","servings":"मतवीनव़","cuisine":"तऩ्","difficulty":"तऩ्","time":"मन्","category":"तऩ्","Easy":"मनव़","Medium":"तऩ्","Hard":"तऩ्","Breakfast":"मतवीनव़","Lunch":"तऩ्","Dinner":"तऩ्","Snacks":"तऩ्","All":"तऩ्","recipeSteps":["आसवम़् तपमन् लिफऩ् सािव़नक् सनमकिताक् सनतग़ नसवम़् सननसकन् तन नसवम़्.","नवतसव़क् पकबसवीस् तपकपौ लिफनप़् मव़तसवपनी पतब्.","त़तौ सवम़क् पतबककनव़ तनीत़ ़नव़ नवमौतन मन. कनव़."]}};

export function translate(k,l){if(!l||l==="en-US")return k;return TRANSLATIONS[l.split("-")[0]]?.[k]??k;}